### ISSUE TITLE
Switching Themes forces the app to crash

### ISSUE THREAD

**Issue by texium** [lukasmonk/lucaschessR2#147]
I switched my theme away from vista or hybrid and now the app doesn't even open. It will pop on in task manager then just die. Not sure what to do, heres the log from the bug text file:
Version R 2.14f
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\embedded.i09trjpy.zip\shibokensupport\signature\loader.py", line 105, in seterror_argument
  File "C:\Users\user\AppData\Local\Temp\embedded.i09trjpy.zip\shibokensupport\signature\errorhandler.py", line 99, in seterror_argument
  File "C:\Users\user\AppData\Local\Temp\embedded.i09trjpy.zip\shibokensupport\signature\mapping.py", line 210, in update
  File "C:\Users\user\AppData\Local\Temp\embedded.i09trjpy.zip\shibokensupport\signature\mapping.py", line 562, in init_PySide2_QtMultimedia

**Comment by lukasmonk** [comment]
I just fixed an update, maybe that was the problem.
Reinstalling the application will probably fix it.

**Comment by texium** [comment]
> I just fixed an update, maybe that was the problem. Reinstalling the application will probably fix it.

it did not fix, i tried installing 2.14l, and 2.13, neither worked

**Comment by lukasmonk** [comment]
In the UserData/__config__ folder, there is a file = lk.pk2, rename it to lk.pk2.old, and launch the program again.
