### ISSUE TITLE
[bug][v2.04] board editor side to play radio buttons do not change side

### ISSUE THREAD

**Issue by Xyrio** [lukasmonk/lucaschessR2#55]
clicking the radio buttons of the gui does not correctly change the side.
copy of fen has then wrong side.

using the circle in the corner of the board does it correctly.

edit: circle in corner works correctly not affecting FEN side just perspective of board

**Comment by lukasmonk** [comment]
Please tell me which radio buttons you are talking about.

**Comment by Xyrio** [comment]
within the "Side to play" group are radio buttons "White" and "Black". if you click them you will see that the circle in the corner of the board changes but the board itself is not flipped. if you press the corner circle it flips board correctly.

**Comment by lukasmonk** [comment]
I am not able to guess where in the program this happens.

**Comment by Xyrio** [comment]
tools -> create your own game -> utilities -> change the starting position -> board editor

**Comment by lukasmonk** [comment]
Fixed to the next update.

**Comment by Xyrio** [comment]
thanks

**Comment by Xyrio** [comment]
fyi: in 2.05 this is still not working. without saving, the change in to White/Black radio buttons is not applied when copy FEN.

**Comment by lukasmonk** [comment]
I know, the update, which resolves the problem, has not been released.

**Comment by Xyrio** [comment]
confirmed working in 2.05d
